# Generated by Django 5.1.6 on 2025-03-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipe_image',
            new_name='image',
        ),
    ]
